name: Ruby Tests

on:
  push:
    branches: [ main ] # Or your default branch, e.g., master
  pull_request:
    branches: [ main ] # Or your default branch

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # These secrets need to be configured in your GitHub repository settings
      # Go to Settings > Secrets and variables > Actions > New repository secret
      SIMPLEPRACTICE_VALID_EMAIL: ${{ secrets.SIMPLEPRACTICE_VALID_EMAIL }}
      SIMPLEPRACTICE_VALID_PASSWORD: ${{ secrets.SIMPLEPRACTICE_VALID_PASSWORD }}
      RAILS_ENV: test # Often useful, though not strictly Rails, it's a common convention

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      # You might want to specify a Ruby version consistent with your development environment
      # e.g., uses: ruby/setup-ruby@v1
      #       with:
      #         ruby-version: '3.1' # Or your project's Ruby version
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1' # Using a recent stable version, adjust if needed
        bundler-cache: true # Automatically runs bundle install and caches gems

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    # The webdrivers gem should handle ChromeDriver if Chrome is present.
    # If you encounter issues with ChromeDriver, you might need an explicit setup step for it.
    # For example, using a specific version:
    # - name: Setup ChromeDriver
    #   uses: nanasess/setup-chromedriver@v2
    #   with:
    #     chromedriver-version: 'latest' # Or a specific version matching your Chrome

    - name: Run RSpec tests
      run: bundle exec rspec

    - name: Generate Allure Report
      if: always() # Run this step even if tests fail to get a report of failures
      uses: simple-elf/allure-report-action@v1.7
      with:
        allure_results: allure-results # This is the default directory where RSpec Allure adapter saves results
        allure_report: allure-report # This is the default directory for the generated Allure report

    - name: Upload Allure Report as Artifact
      if: always() # Also run this step even if tests fail
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report # Path to the directory generated by Allure