name: Ruby Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SIMPLEPRACTICE_VALID_EMAIL: ${{ secrets.SIMPLEPRACTICE_VALID_EMAIL }}
      SIMPLEPRACTICE_VALID_PASSWORD: ${{ secrets.SIMPLEPRACTICE_VALID_PASSWORD }}
      RAILS_ENV: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Verify Chrome and Chromedriver
      run: |
        google-chrome --version
        chromedriver --version

    - name: Run RSpec tests
      run: bundle exec rspec --format documentation

    - name: Generate Allure Report
      if: always()
      uses: simple-elf/allure-report-action@v1.7
      with:
        allure_results: allure-results
        allure_report: allure-report

    - name: Upload Allure Report as Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report